### ISSUE TITLE
Can't execute client

### ISSUE THREAD

**Issue by krakrjak** [icfpcontest2017/lambda-duct#4]
With v0.3 I get a good connection to a port, but eventually it simply drops the connection. Doesn't matter the port used. Here is a transcript of the latest error:
```
krakrjak@zombiebits:~/src/Icfp2017-junkfood$ lamduct --game-hostname punter.inf.ed.ac.uk --game-port 9036 --log-level 3 .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter/punter
lamduct: main: Resolving punter.inf.ed.ac.uk...
lamduct: main: ... resolved to 129.215.197.1.
lamduct: main: Creating TCP connection...
lamduct: main: Connecting to punter.inf.ed.ac.uk:9036...
lamduct: main: Connection established.
lamduct: main: Handshaking with client...
lamduct: main: Invoking program /home/krakrjak/src/Icfp2017-junkfood/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter/punter...
lamduct: main: Changing working directory to: /home/krakrjak/src/Icfp2017-junkfood/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.0.0/build/punter...
lamduct: main: Changing working directory to: /home/krakrjak/src/Icfp2017-junkfood...
lamduct: main: Interacting with client...
lamduct: main: BIO: receiving.
error: client or server connection was dropped.
```

**Comment by dhil** [comment]
Try what I suggested in #3. The problem is likely with your client.

**Comment by krakrjak** [comment]
Okay, I can agree it's likely in the client at this point,but i don't understand what's going on here. Sure it looks like lamduct does a handshake with the client and I see, by using the `--client-instance-logfile /dev/stderr` that my client does output to stderr the handshake request, but not the handshake response thus leading to the dropped connection. i'm mostly looking for debugging pointers i guess.

I must be violating the protocol in some way and I'm not sure what that could be.

**Comment by krakrjak** [comment]
Totally the client program's fault. A little too much laziness went to its head. Keep up the good work.
